# Generated by Django 5.1.1 on 2024-10-06 20:26

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=4, unique=True)),
                ('full_name', models.CharField(max_length=250)),
                ('sector', models.CharField(choices=pages.models.StockInfo.get_list_of_sectors)),
            ],
        ),
    ]
